### ISSUE TITLE
USER STORY: Site information

### ISSUE THREAD

**Issue by andyk8872** [andyk8872/pp4-team-build#1]
As a **user** I can **view the site** so that **I can determine the function/purpose of the site**
  
 ## Acceptenace Critaeria:
  
  * Acceptance Criteria 1: The user can view the various booking options.
  * Acceptance Criteria 2: The user can view a navigation toolbar.
  * Acceptance Criteria 3: The user can view a footer with contact options.
  
## Tasks
  
  - [ ] Task 1: Design the user interface.
  - [ ] Task 2: Create HTML/CSS 
  - [ ] Task 3 Add the relevant information
