### ISSUE TITLE
USER STORY: Staff Access

### ISSUE THREAD

**Issue by andyk8872** [andyk8872/pp4-team-build#14]
As a **site admin** I can **have admin access from the from a html page** so that **preform admin functions**
  
 ## Acceptenace Critaeria:
  
  * Acceptance Criteria 1: I can manage reviews.
  * Acceptance Criteria 2:
  * Acceptance Criteria 3:
  
## Tasks
  
  - [ ] Task 1. Design a staff page.
  - [ ] Task 2: Create HTML/CSS
  - [ ] Task 3: Create the code for the model, view and controller
