### ISSUE TITLE
USER STORY: Add navigation bar

### ISSUE THREAD

**Issue by andyk8872** [andyk8872/pp4-team-build#2]
As a **user** I can **traverse the site** so that **I can fulfil my aims**
  
 ## Acceptenace Critaeria:
  
  * Acceptance Criteria 1: The user can view the links
  * Acceptance Criteria 2: The user can click on the links
  * Acceptance Criteria 3: 
  
## Tasks
  
  - [ ] Task 1 : Design a navigation bar
  - [ ] Task 2: Create HTML/CSS
  - [ ] Task 3 : Add the code links
