### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by andyk8872** [andyk8872/pp4-team-build#3]
As a **user** I can **have the view links** so that **I can link to the sites social media**
  
 ## Acceptenace Critaeria:
  
  * Acceptance Criteria 1: View social media links
  * Acceptance Criteria 2: Click on the links
  * Acceptance Criteria 3:
  
## Tasks
  
  - [ ] Task 1 : Design the footer.
  - [ ] Task 2 : Create HTML/CSS
  - [ ] Task 3 : Add the appropiate code links.
