### ISSUE TITLE
USER STORY: User Login

### ISSUE THREAD

**Issue by andyk8872** [andyk8872/pp4-team-build#4]
As a **site user** I can **login to the site** so that **I can make/view/edit bookings**
  
 ## Acceptenace Critaeria:
  
  * Acceptance Criteria 1: Register as a member.
  * Acceptance Criteria 2: Login as a member.
  * Acceptance Criteria 3: Have the option to logout.
  
## Tasks
  
  - [ ] Task 1: Design the login/logout/register icons.
  - [ ] Task 2: Create the HTML/CSS.
  - [ ] Task 3: Create the code.
