### ISSUE TITLE
USER STORY: Create Booking

### ISSUE THREAD

**Issue by andyk8872** [andyk8872/pp4-team-build#5]
As a **site user** I can **make a booking** so that **fulfil my criteria.**
  
 ## Acceptenace Critaeria:
  
  * Acceptance Criteria 1: Choose the activity option I want.
  * Acceptance Criteria 2: Ensure date availabitty
  * Acceptance Criteria 3: Make the booking.
  
## Tasks
  
  - [ ] Task 1: Design an input form.
  - [ ] Task 2: Ensure validation.
  - [ ] Task 3: Create the code for the model, viewer and controller.
