### ISSUE TITLE
USER STORY: Edit Booking

### ISSUE THREAD

**Issue by andyk8872** [andyk8872/pp4-team-build#6]
As a **site user/admin** I can **edit the booking** so that **make changes**
  
 ## Acceptenace Critaeria:
  
  * Acceptance Criteria 1: Change the date.
  * Acceptance Criteria 2: Change the activity
  * Acceptance Criteria 3: Change my contact details
  
## Tasks
  
  - [ ] Task 1: Create icon to show booking
  - [ ] Task 2: Allow the form details to be edited.
  - [ ] Task 3 : Create the code for the model, view and controller.
