### ISSUE TITLE
USER STORY: Delete Booking

### ISSUE THREAD

**Issue by andyk8872** [andyk8872/pp4-team-build#7]
As a **site user/admin** I can **delete a booking** so that **make other arrangements**
  
 ## Acceptenace Critaeria:
  
  * Acceptance Criteria 1: Access a previous booking.
  * Acceptance Criteria 2: Delete a booking
  * Acceptance Criteria 3:
  
## Tasks
  
  - [ ] Task 1: Design a delete icon.
  - [ ] Task 2: Create the HTML/CSS
  - [ ] Task 3: Create the code for the delete function
