### ISSUE TITLE
USER STORY: View Bookings

### ISSUE THREAD

**Issue by andyk8872** [andyk8872/pp4-team-build#8]
As a **site user/admin** I can **view bookings** so that **review events**
  
 ## Acceptenace Critaeria:
  
  * Acceptance Criteria 1: Access bookings.
  * Acceptance Criteria 2: View bookings.
  * Acceptance Criteria 3:
  
## Tasks
  
  - [ ] Task 1: Design view booking icon.
  - [ ] Task 2: Create HTML/CSS
  - [ ] Task 3 : Create the code for the model, viewer and controller.
